# Validation or Testing
approach: test

train_model: false
straight_to_training: False

# Partial Load for Debugging Code
baseline_candidates:
  load: False
  path: './output/candidates'
  debug: False
  top_n:
    clicks: 80
    buys: 80
    carts: 80
  partial: False
  lims:
    clicks:
      click: 40
      buy: 5
    carts:
      click: 60
      buy: 10
    buys:
      buy: 40
      b2b: 10

# Number of Candidates
candidates: 100
cand_percent: 1.0

# XGB Parameters
xgb:
  learning_rate: 0.1
  max_depth: 6
  num_boost_round: 2_000
  verbose_eval: 100
  early_stopping_rounds: 50
  frac: 0.01
  colsample_bytree: 0.75
  features: './cfgs/xgb-features2.yaml'

# Data
path:
  val:
    base: './data/otto-validation/'
    train: './data/otto-validation/train_parquet'
    test: './data/otto-validation/test_parquet'
    test_labels: './data/otto-validation/test_labels.parquet'
  test:
    base: './data/otto-chunk-data-inparquet-format/'
    train: './data/otto-chunk-data-inparquet-format/train_parquet'
    test: './data/otto-chunk-data-inparquet-format/test_parquet'
  features:
    base: './output/features'

otto_valid_test_list:
  base: './data/otto-valid-test-list'
  val_ver: 1
  test_ver: 1

# Seed
seed: 42

# Type Labels
type_labels: {'clicks': 0, 'carts': 1, 'orders': 2}

# Type Weight Multipliers
type_weight_multipliers: {'0': 0.5, '1': 9, '2': 0.5}

# Co-vis-matrix: 
co_vis_matrix:
  disk_pieces:
  save_path: ./output/co-vis-matrices
  cart_orders: # top_n saved as "carts" but loads "buys"
    overwrite: True
    fun_name: cart_orders
    ver: 0
    file_name: carts_orders
    type_weight: {'0': 0.5, '1': 9, '2': 0.5}
    top_n: 80
  buy_to_buy: # top_n saved as "buys" but load buy2buy
    overwrite: True
    fun_name: buy_to_buy
    ver: 0
    file_name: buy2buy
    type_weight: 1
    top_n: 80
  click: 
    overwrite: True
    fun_name: clicks
    ver: 0
    file_name: clicks
    type_weight: None
    top_n: 80

